version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: talentscout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sans
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d talentscout"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:sans@db:5432/talentscout
      GROQ_API_KEY: ${GROQ_API_KEY}

volumes:
  postgres_data: