app = "hr-assist-llm"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "hr_assist_data"
  destination = "/data"