site_name: Sans AI — HR Assist
site_description: "Company-grade HR assistant powered by LLMs — API docs, deployment, and developer guide"
site_author: OMCHOKSI108
site_url: https://omchoksi108.github.io/hr-assist-llm/
repo_url: https://github.com/OMCHOKSI108/hr-assist-llm
repo_name: OMCHOKSI108/hr-assist-llm
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 OMCHOKSI108

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - header.autohide
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - footnotes

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Configuration: configuration.md
  - API Reference:
    - Overview: api.md
    - Endpoints: api_endpoints.md
  - Frontend: frontend.md
  - Screenshots: screenshots.md
  - Deployment: deployment.md
  - Developer Guide: developer.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OMCHOKSI108/hr-assist-llm
    - icon: fontawesome/solid/globe
      link: https://omchoksi108.github.io/hr-assist-llm/

