[project]
name = "assist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.50.0",
    "torch>=2.8.0",
    "transformers>=4.57.1",
]
